# version: "3.9" No need to specify version, as it is optional and defaults to the latest version

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto

  simulator:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto